### ISSUE TITLE
Crash reporting?

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#201]
Do we want it? do we have it?

**Comment by asutula** [comment]
Doing some research. I think the two best options are:

1. https://docs.microsoft.com/en-us/appcenter/sdk/crashes/react-native
2. https://github.com/corymsmith/react-native-fabric + something like https://github.com/mikelambert/react-native-fabric-crashlytics

1 .might already be almost working since we've already the AppCenter SDK into the app. 

The goal should be to have native crashes reported as well as any JS layer un-handled exceptions or crashes. Both 1. and 2. provide that.

**Comment by asutula** [comment]
Ok, went through our setup to find.... Crash reporting was already setup and is, in fact, working. Check out the AppCenter dashboard and you will see crashes, even from our most recent Testflight build a couple hours ago.

I went ahead and updated the Appcenter npm module and Cocopods, verified everything is setup correctly.

**Comment by asutula** [comment]
I'll create a ticket for this, but we'll want to create an iOS build artifact which is the javascript source map of the app. I guess to get the full shebang of AppCenter crash reporting, it has to be uploaded with the dsym.
