### ISSUE TITLE
Visual feedback for clicking the share text button

### ISSUE THREAD

**Issue by thorsten-panknin** [textileio/textile-mobile#499]
Huawei P9 lite, Android 7, Textileversion 1.6.6

I noticed that clicking the share button to add a photo to a thread does not yield any visual feedback that the text button has been clicked. The UI simply does nothing for a second or two.

Futhermore, I was confused by the term "share". I have a basic grasp of how IPFS works, but I would've expected something like "add".

**Comment by asutula** [comment]
Can you give a little more information about what screen of the app you're sharing an image from? I'm a little confused because your description makes it sound like you see a button labeled 'Share', but you should be seeing icons, not words. Are you running your phone in some sort of accessibility mode?

**Comment by asutula** [comment]
Ah it seems you're talking about the screen where you enter a caption and then tap the 'Share' button...  When you tap that button, it should immediately go back to the screen for the thread you're sharing to, and you should see some UI displaying the progress of sharing that image. I'll have to test that out on Android to make sure it's working as expected.

**Comment by carsonfarmer** [comment]
Another user has reported a similar issue. Testing on Android, it seems the user _is_ taken to the upload progress screen. Perhaps this has been fixed with a more recent update?

**Comment by asutula** [comment]
The UI has been updated a bit since this was discussed previously. Testing here on my device, the share button does show some feedback and the app navigates to another screen showing the share/upload progress. Closing for now, but if this is still a problem after the next release (which should be out in the next couple weeks), let's re-open.
