### ISSUE TITLE
Placeholder text for feed view when empty

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#513]
(it's just blank white right now)

Should this be something like we display for the wallet and threads tours?

**Comment by asutula** [comment]
Could be a juicy one for you @carsonfarmer

**Comment by carsonfarmer** [comment]
We do currently have this similar to wallet and threads tours. I think the issue here is that, once you tap 'cool', there's nothing there... but this is what we do with the thread view as well. It is blank until a thread has been created or joined. Maybe we should add some text for both of these views?

**Comment by asutula** [comment]
Just figured if there are no photos in a thread, we should display this placeholder content and that content should have a button that says "share photo" or point the user to the share photo button in the nav bar.

**Comment by asutula** [comment]
So this isn't some tour screen they can dismiss. It will always display if there are no photos in the thread.

**Comment by carsonfarmer** [comment]
From discussion on slack:
> actually, i guess its multiple things
> we should have placeholder text with 'action' buttons for all of them
> just went through:

-[] empty thread list is blank
-[] empty thread is blank
-[] empty feed view is blank

There are already SB designs for these, so we can use those.

**Comment by carsonfarmer** [comment]
Update: the above views are all setup, but leads to quick flash when firing up because we don’t persist thread/photo data, and the queries to grab thread data are async. So checking if a thread list is empty will show up as 0 for a split second while that query happens. 
'Solution' seems to be to make the `treads` redux property optional, so then we'd interpret `undefined` as “doesn’t yet exist”... working on that now

**Comment by carsonfarmer** [comment]
Fixed with #521
