### ISSUE TITLE
pinch zoom an image

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#514]

**Comment by andrewxhill** [comment]
Not super straight-forward actually.

You can wrap it in a ScrollView to get close, but a few issues arise. You could use https://www.npmjs.com/package/react-native-pinch-zoom-view but nice things like having the view snap back on release aren't built in. It also would take some css tweaking to get the image outside of the view, so that it pinches over the entire screen.

Finally, there is this https://github.com/alwx/react-native-photo-view which might have the blueprint for enabling pinch/zoom as a flag on the native textileimages.
