### ISSUE TITLE
In New Comment notification (feed) take clicks to the photo view

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#675]
Right not it takes the user to the Add comment view

But pet peeve i've heard is then the user can't remember what photo it was. 

If we just take them to the Photo view, all comments are expanded in that view anyway so it serves both purposes.

**Comment by asutula** [comment]
Right now, the single photo view shows a configurable number of comments. We can configure it to show all comments and change the notification handler to navigate to it instead of the comments screen. If showing all comments isn't desirable, we can add a feature  where it show at most n comments including the comment with a specific id. That id would be set to the notification comment id.
